2019-03-14 16:00:51,930 - IIot platform - ERROR - Object of type bytes is not JSON serializable
2019-03-14 17:08:57,859 - IIot platform - ERROR - 'ClientDevicesResponse' object has no attribute 'MessageToJson'
2019-03-14 17:09:50,072 - IIot platform - ERROR - 'ClientDevicesResponse' object has no attribute 'MessageToJson'
2019-03-15 10:31:54,390 - IIot platform - ERROR - Assignment not allowed to field "devicelist" in protocol message object.
2019-03-15 10:38:04,858 - IIot platform - ERROR - 'ClientDevicesResponse' object has no attribute 'add'
2019-03-15 16:28:46,575 - IIot platform - ERROR - 'DeviceDataRequest' object has no attribute 'getDevEuiList'
2019-03-15 17:09:31,816 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'list'
2019-03-15 17:10:25,999 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'list'
2019-03-15 17:11:58,627 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'list'
2019-03-15 17:12:19,320 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'list'
2019-03-15 17:12:30,236 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-15 17:13:35,669 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-15 17:16:13,471 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-15 17:22:57,746 - IIot platform - ERROR - 'ResultProxy' object has no attribute 'fatchall'
2019-03-15 17:23:29,701 - IIot platform - ERROR - 'list' object has no attribute 'SerializeToString'
2019-03-18 11:30:40,129 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-18 11:31:52,140 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-18 14:34:33,175 - IIot platform - ERROR - getDeviceDataHistory() missing 2 required positional arguments: 'dev_lst' and 'ts'
2019-03-18 14:35:18,617 - IIot platform - ERROR - replace() argument 2 must be str, not google.protobuf.pyext._message.RepeatedScalarConta
2019-03-18 14:36:23,270 - IIot platform - ERROR - replace() argument 2 must be str, not Timestamp
2019-03-18 14:36:58,385 - IIot platform - ERROR - replace() argument 2 must be str, not int
2019-03-18 16:49:03,967 - IIot platform - ERROR - Assignment not allowed to field "ts" in protocol message object.
2019-03-18 16:50:47,132 - IIot platform - ERROR - datetime.datetime(2019, 3, 15, 10, 10, 39, 848637) has type datetime.datetime, but expected one of: int, long
2019-03-18 16:54:48,825 - IIot platform - ERROR - 1552633839.0 has type float, but expected one of: int, long
2019-03-18 16:55:09,848 - IIot platform - ERROR - Assignment not allowed to field "ts" in protocol message object.
2019-03-18 17:02:14,140 - IIot platform - ERROR - '26' has type str, but expected one of: int, long, float
2019-03-18 17:02:52,114 - IIot platform - ERROR - No positional arguments allowed
2019-03-18 17:17:47,737 - IIot platform - ERROR - 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'
2019-03-20 10:38:13,411 - IIot platform - ERROR - 'EnumTypeWrapper' object has no attribute 'DEVICE_LIST_REQUEST'
2019-03-20 10:40:09,019 - IIot platform - ERROR - 'EnumTypeWrapper' object has no attribute 'DEVICE_LIST_REQUEST'
2019-03-20 10:52:01,963 - IIot platform - ERROR - 'EnumTypeWrapper' object has no attribute 'DEVICE_DATA_HISTORY_RESPONSE'
2019-04-15 16:50:34,267 - IIot platform - ERROR - <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1555336234.265345000","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2706,"referenced_errors":[{"created":"@1555336234.265332000","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":242,"referenced_errors":[{"created":"@1555336234.265139000","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":867,"grpc_status":14,"referenced_errors":[{"created":"@1555336234.265097000","description":"Failed to connect to remote host: FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.cc","file_line":532,"grpc_status":14,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1555336234.265053000","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":119}],"target_address":"ipv4:192.168.10.28:8080"}]}]}]}"
>
2019-04-15 16:53:22,178 - IIot platform - ERROR - '8' has type str, but expected one of: int, long
2019-04-19 17:22:28,610 - IIot platform - ERROR - 'SiburLab'
2019-04-19 17:28:23,894 - IIot platform - ERROR - 'SiburLab'
2019-04-19 17:29:22,713 - IIot platform - ERROR - 'SiburLab'
2019-04-22 17:43:12,822 - IIot platform - ERROR - <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "authentication failed: jwt parse error: illegal base64 data at input byte 1"
	debug_error_string = "{"created":"@1555944192.822591000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"authentication failed: jwt parse error: illegal base64 data at input byte 1","grpc_status":16}"
>
2019-04-22 17:44:54,271 - IIot platform - ERROR - <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "authentication failed: jwt parse error: illegal base64 data at input byte 1"
	debug_error_string = "{"created":"@1555944294.271518000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"authentication failed: jwt parse error: illegal base64 data at input byte 1","grpc_status":16}"
>
